### ISSUE TITLE
installer script overwrite nvencodeapi, nvcuvid and nvcuda libs

### ISSUE THREAD

**Issue by sl1pkn07** [SveSop/nvidia-libs#1]
Hi

Actually, the installer overwrite with symlinks the libraries  `nvencodeapi.dll`, `nvcuvid.dll` and `nvcuda.dll`, wich is already included if build wine(staging) with cuda support

instead of this, is possible make a backup of the libraries before creating the symlinks? and back it when run the uninstall like do dxvk

greetings

**Comment by SveSop** [comment]
Well, when you run "uninstall", the script should do a `wineboot -u` and wine would (should) then replace the missing fakedll's with the original ones.
Does it not do that? If so.. what wine-staging version?

**Comment by sl1pkn07** [comment]
I have not tried to uninstall it, I have only tried to install it

**Comment by SveSop** [comment]
`wineboot -u` will not overwrite files already there - or symlinks. So when you either copy "custom dll's" or create symlinks in the wineprefix, `wineboot -u` will not touch those.

However, if the files are missing from the wineprefix, they will be recreated from this command. The "uninstall" function of my script simply deletes the symlinks, and remove the overrides.. and when it is done, it will run `wineboot -u` and the original .dll's and fakedll's will be put into the wineprefix again - assuming ofc that you are still running with wine-staging.

Creating a prefix with wine-staging, install nvidia-libs and then switch to wine-devel and THEN uninstall will NOT recreate the files, since wine-devel does not contain nvapi libs :)

Although probably "convenient" to create backups for the above mentioned reason (if switching between wine-devel and wine-staging), i would kinda say "it is not meant for that" :smile:
