### ISSUE TITLE
nvapi64-tests failing

### ISSUE THREAD

**Issue by Maxwellfire** [SveSop/nvidia-libs#10]
I'm trying to get the nvapi working in wine, and I'm not able to run the tests successfully.

When running `nvapi64-tests.exe` I get:

```
nvapi64-tests.exe is a Catch2 v3.4.0 host application.
Run with -? for options

-------------------------------------------------------------------------------
Sysinfo methods succeed against local system
-------------------------------------------------------------------------------
../../../dxvk-nvapi/tests/nvapi_system.cpp:78
...............................................................................

../../../dxvk-nvapi/tests/nvapi_system.cpp:156: FAILED:
  REQUIRE( nvAPI_Initialize() == NVAPI_OK )
with expansion:
  -6 == 0

===============================================================================
test cases:  1 |  0 passed | 1 failed
assertions: 63 | 62 passed | 1 failed
```

[This error seems to indicate](https://docs.nvidia.com/gameworks/content/gameworkslibrary/coresdk/nvapi/group__nvapistatus.html#gga12534f3b520256799842c0172e9afdf7a28605e58276840c3207a211620569345) that the nvapi is able to be queried, but that it's reporting that I don't have an NVIDIA GPU installed. I don't get anything printed in the logs when using the recommended `WINEDEBUG` value.

My system is an optimus setup with both a `NVIDIA GeForce GTX 1050` and an `Intel(R) HD Graphics 630`. 

GPU caps viewer reports things mostly correctly:
[gpu_caps_viewer_report.txt](https://github.com/SveSop/nvidia-libs/files/12776671/gpu_caps_viewer_report.txt)

It does seem to find the `Wine Adapter` in the GPU info though.

I installed the NVML libraries to my wine binaries folder as described [here](https://github.com/Saancreed/wine-nvml).

Tested with `wine-8.17` and `wine-8.17 (Staging)`

**Comment by SveSop** [comment]
I think you should try to run the tests with:
`DXVK_NVAPI_LOG_LEVEL=info WINEDEBUG=-all,+nvml`

I suspect it is due to having two adapters.

```
===================================[ Graphics Adapters / GPUs ]
- Current Display Mode: 3840x2160 @ 60 Hz - 32 bpp
- Num GPUs: 1

- GPU 1
  - Name: Wine Adapter

```
This is not correct. GPU Caps viewer should not report "Wine Adapter" tbh. There is a wine bug in wine 8.xx where this happens if you run something using "Virtual Desktop" setting. The "Wine Adapter" is then the FIRST adapter and that does not work with nvapi and friends.

You could also try fidding with how DXVK detects adapters according to: https://github.com/doitsujin/dxvk#device-filter as i think some manual tweakage is needed when having multiple/optimus kind of setups (which i do not, and cant really test).

Also you could look at DXVK's logs with `DXVK_LOG_LEVEL=info` or other tools like vulkaninfo and see what adapter(s) is listed there.

**Comment by Maxwellfire** [comment]
Interesting, so I got gpu_caps_viewer to report the right value. Turns out that I hadn't loaded dxvk in my prefix. With that, the nvapi tests succeed. (I don't quite understand why dxvk is necessary since I thought nvapi was a separate gpu interface than directx?).

I'll followup in the other issue then, since that still doesn't work for me.

**Comment by SveSop** [comment]
> Interesting, so I got gpu_caps_viewer to report the right value. Turns out that I hadn't loaded dxvk in my prefix. With that, the nvapi tests succeed. (I don't quite understand why dxvk is necessary since I thought nvapi was a separate gpu interface than directx?).
> 
> I'll followup in the other issue then, since that still doesn't work for me.

NVAPI is called DXVK-NVAPI because it uses various vulkan info from dxvk to get values for nvapi, else it would mostly just be "invented values". More info here https://github.com/jp7677/dxvk-nvapi

NVAPI has no linux equvalent and thus do not "talk to" the gpu, as this is low-level api stuff that is hard if not impossible to actually implement for linux. I guess if someone would write a nvapi implementation for nouveau driver (the opensource linux driver) it could be done, but it would require THAT kind of implementation. That is the reason why DXVK-NVAPI needs stuff like DXVK and nvml to get more indepth info from the adapter. (Still impossible to implement loads of stuff tho).
