### ISSUE TITLE
Supersonic Sled Nvidia demo with CUDA

### ISSUE THREAD

**Issue by WinterSnowfall** [SveSop/nvidia-libs#18]
I'm trying to run the [Supersonic Sled Nvidia demo](https://www.nvidia.com/en-us/geforce/community/demos/) in Wine, ~~but it complains about not being able to load nvcuda.dll.~~

~~`0138:err:module:import_dll Library nvcuda.dll (which is needed by L"C:\\Applications\\Nvidia Sample Apps\\Supersonic Sled\\bin\\SupersonicSled.exe") not found`~~

~~I have placed the nvcuda.dll files in the right locations and also have a native Wine overrride in place, so I'm not sure what's missing. Are there any additional setup steps required? Something in the registry perhaps?~~

Nevermind the above, I had misinterpreted the install instructions and was using the windows dlls stubs with Wine. Now I've hit another problem however:

```
0024:trace:nvcuda:DllMain (0x7e850000, 1, 0xa1fd24)
0024:fixme:nvcuda:load_functions Wine cannot find the cuda library, CUDA support is disabled.
0024:trace:nvcuda:DllMain (0x7e850000, 0, 0xa1fd24)
0024:err:module:loader_init "nvcuda.dll" failed to initialize, aborting
```
64-bit CUDA seems to load just fine, but 32-bit CUDA does not (at least not in WOW64 Wine, I have not tried a pure 32-bit prefix).

**Comment by SveSop** [comment]
I am a bit uncertain what you mean by "WOW64 wine", as there is two ways to interpret that.

Are you talking about using the wineprefix as 32-bit? (Like 32-bit windows), or are you talking about wine itself compiled as the new "WOW64" mode? If you are talking about the first, it should work.. however if you are using wine compiled as WOW64, 32-bit is not supported for nvcuda. https://github.com/SveSop/nvidia-libs/issues/7#issuecomment-2003879458

As i kind of tries to convey in that post, this would require a massive overhaul of the library.. and i am not sure i am even capable tbh 😢 The other part is that 32-bit cuda is probably not used for anything after 2015'ish or so... so about 10 years. The SuperSonic Sled demo is from 2010 or so, so putting down an extreme amount of work and/or testing just for 32-but cuda is not really something i am considering, since you could easily enough just use a "regular" or older version of wine. (I know this will change when distro's stop supporting 32-bit libs altogether.. but then so would the nvidia driver aswell i would say).

To top this off once you use a correct version of wine, an updated version of nvapi with a fix that does not really do much, it still wont work at this point. (Still investigating and testing as we speak.. but need some more debugging to figure out why it actually crashes where it does).

Oh.. and for this demo you also need the following things installed (via winetricks as this is most conventient).
`WINEPREFIX=/your/prefix winetricks PhysX d3dx11_43 d3dcompiler_43` (replacing WINEPREFIX with your prefix ofc)

So.. yeah.. not the easiest demo to get working 😄 

PS. Just a thought: Your nvidia driver is installed with 32-bit library support i hope? Depending on distro this may be different, but i tend to use the nvidia installer .sh script, and it will ASK if you want the 32-bit library support files installed which is crucial for 32-but nvcuda functionality.

**Comment by WinterSnowfall** [comment]
> Are you talking about using the wineprefix as 32-bit? (Like 32-bit windows), or are you talking about wine itself compiled as the new "WOW64" mode? If you are talking about the first, it should work.. however if you are using wine compiled as WOW64, 32-bit is not supported for nvcuda. [#7 (comment)](https://github.com/SveSop/nvidia-libs/issues/7#issuecomment-2003879458)

My comment was mostly on the lines that I know there are 32-bit applications out there that still take issues when run in a WOW64 (64-bit) prefix. That being said, I have been using a mixed 64-bit (WOW64) prefix for ages and haven't really had any issues with any 32-bit apps in it so far. And by "apps" I mostly mean games.
 
> As i kind of tries to convey in that post, this would require a massive overhaul of the library.. and i am not sure i am even capable tbh 😢 The other part is that 32-bit cuda is probably not used for anything after 2015'ish or so... so about 10 years. The SuperSonic Sled demo is from 2010 or so, so putting down an extreme amount of work and/or testing just for 32-but cuda is not really something i am considering, since you could easily enough just use a "regular" or older version of wine. (I know this will change when distro's stop supporting 32-bit libs altogether.. but then so would the nvidia driver aswell i would say).

Well yes, I agree it's no longer used for anything recent, but there are plenty of older 32-bit games that use it, mostly ones that are on Unreal Engine 3, like Batman: Arkham Asylum, Mirror's Edge, Unreal Tournament 3 etc. Exclusive 32-bit prefixes are going to become fully obsolete and deprecated at some point, so I'd argue something will need to be done eventually (I understand it's quite the technical challenge, but that doesn't make it less of a problem).
 
> To top this off once you use a correct version of wine, an updated version of nvapi with a fix that does not really do much, it still wont work at this point. (Still investigating and testing as we speak.. but need some more debugging to figure out why it actually crashes where it does).

A pity, but I'm not even at the point where this is a problem yet :).

> Oh.. and for this demo you also need the following things installed (via winetricks as this is most conventient). `WINEPREFIX=/your/prefix winetricks PhysX d3dx11_43 d3dcompiler_43` (replacing WINEPREFIX with your prefix ofc)

Well, getting past the cuda loading issue at first would be nice, then I'll bother with the rest.

> PS. Just a thought: Your nvidia driver is installed with 32-bit library support i hope? Depending on distro this may be different, but i tend to use the nvidia installer .sh script, and it will ASK if you want the 32-bit library support files installed which is crucial for 32-but nvcuda functionality.

I would have also hoped the same, as I think I have all the needed 32-bit libraries installed, but unfortunately the 32-bit Linux version of CUDA-Z doesn't properly detect CUDA support either. Seems like I have some digging to do on this, thanks for the tip.

That being said, at this point do you recommend simply not using/bothering with the 32-bit version of the CUDA library you ship when using WOW64 Wine prefixes?

**Comment by WinterSnowfall** [comment]
> I would have also hoped the same, as I think I have all the needed 32-bit libraries installed, but unfortunately the 32-bit Linux version of CUDA-Z doesn't properly detect CUDA support either. Seems like I have some digging to do on this, thanks for the tip.

As a follow-up to that, for any sad souls that may end up on these pages in the future, let me note that with Ubuntu and derivatives you need to make sure the `libnvidia-compute-x:i386` package for your driver is installed, in order to get 32-bit CUDA support.

**Comment by WinterSnowfall** [comment]
So, as an update on the main topic of this issue, Supersonic Sled seems to work just fine. 

<details>

<summary>See here</summary>

![SSled](https://github.com/SveSop/nvidia-libs/assets/6306593/4d118ce9-7b14-4f7c-8704-46b63c9cc8e6)

</details>


There are a bunch of warnings such as:
```
fluid_updateParticles() failed to launch error = 8
fluid_offsetVelocities() failed to launch error = 8
```
But I'm not entirely sure if that's relevant for your CUDA lib or it's just the drivers being a bit too new at this point.

Thanks for your support!

**Comment by SveSop** [comment]
Oh.. interesting, cos i cant get it to work for me! 😮 
What driver, dxvk version are you using?

**Comment by WinterSnowfall** [comment]
> Oh.. interesting, cos i cant get it to work for me! 😮

It does tend to crash at times during the loading screen, but usually it starts up fine and works equally fine. I'm on Wine Staging 9.4 with Nvidia 535.161.07, and using dxvk - not sure if any of it matters but WineD3D has been rather iffy of late.

**Comment by SveSop** [comment]
It does not look like any DXVK version i have used?? DXVK D8VK as your screenshot sais? 
Some special binary?

**Comment by WinterSnowfall** [comment]
> It does not look like any DXVK version i have used?? DXVK D8VK as your screenshot sais? Some special binary?

That's just my local/custom d8vk build :sweat_smile:. I expect the latest dxvk to work as well, but d8vk is currently based on dxvk 2.2.

**Comment by SveSop** [comment]
So.. custom D8VK with D3D11 versions of DXVK aswell? (Since D8VK is D3D8, and not D3D11)

**Comment by WinterSnowfall** [comment]
> So.. custom D8VK with D3D11 versions of DXVK aswell? (Since D8VK is D3D8, and not D3D11)

It's a fork of dxvk, so it will have everything dxvk has + support for d3d8.

**Comment by SveSop** [comment]
Ah.. oki.. so basically DXVK + D8VK custom added in as some sort of subproject or sumtin..

Well.. i still keep crashing tho. Nice you got it working 😄

**Comment by WinterSnowfall** [comment]
> Ah.. oki.. so basically DXVK + D8VK custom added in as some sort of subproject or sumtin..

Don't worry too much about my dev d8vk version, base dxvk should work just fine :).

> Well.. i still keep crashing tho. Nice you got it working 😄 (550.54.14 driver)

Might want to try running it in a virtual Wine desktop maybe? Depending on your compositor that may or may not be a problem at times with fullscreen apps. I'm on MATE.

**Comment by SveSop** [comment]
No dice with that... Could you possibly post a .zip'ed log for me?
Run with WINEDEBUG=-all,+nvcuda and ill take a look at the nvcuda calls.

**Comment by WinterSnowfall** [comment]
Sure, here it is: [SupersonicSled.log](https://github.com/SveSop/nvidia-libs/files/14668577/SupersonicSled.log)

**Comment by SveSop** [comment]
Thank you 😄 
Our logs seem quite similar, but i crash in the middle of some TLS_CALLBACK's that is not really making sense.. so i think it is something else.. Well, atleast i got something to fiddle with 😏

**Comment by WinterSnowfall** [comment]
I would try to start it several times. I've had instances of 3 consecutive crashes until it started properly on the 4th. At other times it just works on the first try.

**Comment by SveSop** [comment]
If i had $1 every time i tried to start this now... i would pay someone to fix it 😏

**Comment by SveSop** [comment]
Still struggling with this, but i believe this to be some missing winetricks thing in wine and not cuda/nvapi. 

Any particular thing you did? Can you actually get this demo to run with ONLY `physx d3dx11_43 d3dcompiler_43` using regular wine-staging-9.4 and dxvk? Or did you test this with some proton'ish package of wine, and/or in some WINEPREFIX that has a lot of overrides?

I seem to remember running this demo a long while back, and that i had to install something that had to do with playing some video just as the "game" starts, but i don't remember what it was.. Some wmv video playing perhaps? (Tried with WMP9 winetrick and directshow to no avail).

**Comment by SveSop** [comment]
Oki... i was right about the video that plays at the start (black and white video). Had to narrow it down a bit, since i tried a lot of media related winetricks verbs, but this seems to be what is needed:

Fresh wineprefix (wine-staging-9.4)
install DXVK
install nvidia-libs (nvapi/nvcuda)
`winetricks physx d3dx11_43 d3dcompiler_43 lavfilters directshow wmp11`

That made it work. Ill take a closer look at the cuda function "cuModuleLoadFatBinary" as that seems to be loaded, but is currently disabled as i cant quite get it to work atm.. but it could perhaps do "something" or benefit performance in some way perhaps. Anyway 😄

**Comment by WinterSnowfall** [comment]
Glad you figured it out :+1: . To be honest I'm using a rather ancient Wine prefix with a lot things applied to it (I can't even remember everything). It most likely has all the native d3dcompiler libraries, not sure about the rest. I don't get any video playback at the start, but I guess clicking frantically might have skipped it :laughing:.
